### ISSUE TITLE
JSXHint doesn't lint errors (config via .jshintrc)

### ISSUE THREAD

**Issue by voronianski** [SublimeLinter/SublimeLinter-jsxhint#16]
I have installed both `SublimeLinter-jsxhint` and `SublimeLinter-jshint` installed in my Sublime 3.

Files with `.js` extension are linted fine (as it was before) but files with `.jsx` extension are not linted at all.. I have `.jshintrc` in the root folder as always. It's content:

```json
{
    "predef": [
        "after",
        "afterEach",
        "angular",
        "before",
        "beforeEach",
        "define",
        "describe",
        "expect",
        "it",
        "xit",
        "xdescribe",
        "should"
    ],

    "asi" : false,
    "bitwise" : true,
    "browser": true,
    "boss" : false,
    "curly" : true,
    "debug": false,
    "devel": false,
    "eqeqeq": true,
    "evil": false,
    "esnext": true,
    "expr": true,
    "forin": false,
    "immed": true,
    "indent": 4,
    "latedef" : false,
    "laxbreak": false,
    "multistr": true,
    "newcap": true,
    "noarg": true,
    "node" : true,
    "noempty": false,
    "nonew": true,
    "onevar": false,
    "plusplus": false,
    "quotmark": "single",
    "regexp": false,
    "strict": true,
    "sub": false,
    "trailing" : true,
    "undef": true,
    "unused": "vars"
}
```

Do I need to add some additional configuration for `.jsx` files?

**Comment by STRML** [comment]
Are you sure you are using the JavaScript (JSX) syntax pack for JSX
files? It is required for sublimelinter-jsxhint to detect that it should
lint a file.

**Comment by voronianski** [comment]
@STRML I have such packages https://github.com/allanhortle/JSX and https://github.com/reactjs/sublime-react

**Comment by STRML** [comment]
Okay. Sometimes we've seen conflicts between them. TBH, I should remove
the JSX syntax type from this package as most people have already
installed one, and I am not interested in maintaining a syntax package
as well as a linting package.

Could you iterate through your syntax types and see if that gets it to
start linting? If not, please check your console (ctrl-tilde) and see if
you have any messages there.

**Comment by voronianski** [comment]
@STRML yeah, I've found another `JavaScript (JSX)` in the list of extensions and linting began to work.

**Comment by STRML** [comment]
Cool. It might have something to do with the name of the syntax
definition. If you can trace it down let me know and I'll work on a patch.

**Comment by voronianski** [comment]
@STRML also I'm experiencing a lot of linting warnings `'String must use singlequote'` because I prefer to have explicit rule ` "quotmark": "single"` in `.jshintrc`. 

Maybe you know some solution to have this rule but to not lint markup part of jsx?

**Comment by STRML** [comment]
Unfortunately at this time there is no explicit solution for that. You
generally just need to place a conforming jshintrc in the folder to
squelch this.

There are a few open issues claiming the same thing, as well as some
issues on react-tools itself. I don't have any way to transform output
created by react-tools.

In the hopefully near future ESLint will do a more thorough job of
linting the actual pre-transformation content and we can deprecate this
project.

**Comment by voronianski** [comment]
@STRML thanks for a quick answer

**Comment by voronianski** [comment]
> It might have something to do with the name of the syntax
definition. If you can trace it down let me know and I'll work on a patch.

Is there a way to get that name?

**Comment by STRML** [comment]
Yeah, see
https://github.com/SublimeLinter/SublimeLinter-jsxhint/blob/master/linter.py#L23

**Comment by voronianski** [comment]
@STRML They are both `JavaScript (JSX)`, see screenshot:

<img src="https://dl.dropboxusercontent.com/u/100463011/jsxhint-jsx.png" width="500">

The selected one is that works fine with linter.

**Comment by STRML** [comment]
@voronianski As of `1.1.0` the bundled JSX syntax has been removed. Please let me know if you still have this problem. Try 6to5-sublime.

**Comment by STRML** [comment]
Please reopen if you still have an issue.
