### ISSUE TITLE
Can't get ST3 to use jsxhint instead of jshint

### ISSUE THREAD

**Issue by dwayne-roberts** [SublimeLinter/SublimeLinter-jsxhint#29]
Hi guys, 

I just can't seem to get Sublime to use the right linter.

I installed Babel, jsxhint and sublimelinter-jsxhint. The syntax on my *.jsx and *.js files are set to Javascript (Babel). I even tried disabling the native 'JavaScript' syntax package.

But still I get errors when linting via Sublime Text because it's not recognizing the jsx syntax.

```
2 errors 
SublimeLinter: jshint: App.jsx ['C:\\Users\\Dwayne\\AppData\\Roaming\\npm\\jshint.cmd', '--verbose', '--filename', '@', '--config', 'C:\\Program Files (x86)\\xampp\\htdocs\\test\\react-flux\\.jshintrc', '-'] 
SublimeLinter: jshint output:
C:\Program Files (x86)\xampp\htdocs\test\react-flux\src\js\App.jsx: line 8, col 28, Unclosed regular expression. (E015)
C:\Program Files (x86)\xampp\htdocs\test\react-flux\src\js\App.jsx: line 8, col 28, Unrecoverable syntax error. (57% scanned). (E041)

2 errors 
```
Anybody have any ideas on how to fix this?

I'm on a Windows 7 PC using...
- Sublime Text 3 Build 3083
- jshint version 2.7.0
- jsxhint version  0.14.0
- sublimelinter-jsxhint version 1.1.1
- babel-sublime version 5.0.5

**Comment by STRML** [comment]
Ensure that you don't have anything conflicting in your SublimeLinter
User settings that might be setting "javascript (Babel)" to
"javascript", or a .sublimelinterrc file somewhere that is forcing use
of jshint.

**Comment by dwayne-roberts** [comment]
Thanks @STRML, I did indeed have "javascript (babel)" mapped to "javascript". I thought that was mandatory somehow. It works now!

**Comment by tnrich** [comment]
+1 thanks this helped me a lot! Tricky tricky.

**Comment by vynogradskyi** [comment]
should i just delete the "javascript (babel)": "javascript"?

**Comment by STRML** [comment]
Yes.

**Comment by vynogradskyi** [comment]
Does the order of installation of Sublime-linter, Sbulime-linter-jsxhint, jsxhint may cause such issue?

**Comment by STRML** [comment]
No, it shouldn't.

By the way, if you are using this for React code, I would recommend https://github.com/roadhump/SublimeLinter-eslint instead - jsxhint has been deprecated.

**Comment by vynogradskyi** [comment]
I've installed eslint, but the problem still exist, btw, i have JavaScript in right bottom corner. When i click on JavaScript i see numerous types where i'm trying to find 'jsx', 'javascript(jsx)', 'react' or anythiing, but i can't. Does that mean that i didn't install smth?

**Comment by vynogradskyi** [comment]
okay, solved, with eslint

**Comment by SachaG** [comment]
Just wanted to say this helped me as well (using eslint too).
