### ISSUE TITLE
jsxhint does not work correctly

### ISSUE THREAD

**Issue by littlee** [SublimeLinter/SublimeLinter-jsxhint#31]
I install SublimeLinter
I install SublimeLinter-jshint
I install SublimeLinter-jsxhint
I install sublime-babel
I install `npm install -g jshint`
I install `npm install -g jsxhint`
But seems jsxhint not working in jsx file
![jsx](https://cloud.githubusercontent.com/assets/7534668/9597830/46b98864-50b8-11e5-847e-fcbd48de84d4.png)

**Comment by STRML** [comment]
That's because your syntax type is `JavaScript (Babel)` when it should be `JavaScript (JSX)`.

In any case, use [ESLint](http://eslint.org/) and [SublimeLinter-ESLint](https://github.com/roadhump/SublimeLinter-eslint) instead, which gives better errors and has fewer problems with ES6.
