### ISSUE TITLE
Provide .jsxhintrc alternative

### ISSUE THREAD

**Issue by mathieumg** [SublimeLinter/SublimeLinter-jsxhint#7]
Would there be any way to provide a different configuration file to jsxhint/jshint when dealing with JSX files? I would love for my .jsx files to follow a slightly different linting than my .js files in general. As far as I can see, the .jshintrc is currently hardcoded in the Python script. Thank you!

**Comment by STRML** [comment]
This is in `1.1.0`, thanks for the patience.

**Comment by mathieumg** [comment]
Yay! Thank you. :smile:
